import { Task, User, Project } from '@/store/useKanbanStore';
import { generateId } from './utils';

export const seedInitialData = () => {
    const now = new Date();

    const initialUsers: User[] = [
        {
            id: 'user-1',
            name: 'João Silva',
            email: 'joao@kanbanpro.com',
            role: 'admin',
            status: 'online',
            lastSeen: now,
        },
        {
            id: 'user-2',
            name: 'Maria Santos',
            email: 'maria@kanbanpro.com',
            role: 'member',
            status: 'online',
            lastSeen: now,
        },
        {
            id: 'user-3',
            name: 'Pedro Costa',
            email: 'pedro@kanbanpro.com',
            role: 'member',
            status: 'away',
            lastSeen: now,
        },
        {
            id: 'user-4',
            name: 'Ana Oliveira',
            email: 'ana@kanbanpro.com',
            role: 'viewer',
            status: 'offline',
            lastSeen: now,
        },
    ];

    const initialProjects: Project[] = [
        {
            id: 'project-1',
            name: 'Desenvolvimento',
            description: 'Projetos de desenvolvimento de software',
            color: '#3b82f6',
            createdAt: now,
            updatedAt: now,
            members: ['user-1', 'user-2'],
            ownerId: 'user-1',
            isArchived: false,
        },
        {
            id: 'project-2',
            name: 'Design',
            description: 'Projetos de design e UX',
            color: '#10b981',
            createdAt: now,
            updatedAt: now,
            members: ['user-1', 'user-3'],
            ownerId: 'user-1',
            isArchived: false,
        },
        {
            id: 'project-3',
            name: 'Marketing',
            description: 'Campanhas e estratégias de marketing',
            color: '#f59e0b',
            createdAt: now,
            updatedAt: now,
            members: ['user-2', 'user-4'],
            ownerId: 'user-2',
            isArchived: false,
        },
    ];

    const initialTasks: Task[] = [
        {
            id: generateId(),
            title: 'Implementar WebSocket',
            description: 'Configurar Socket.io para atualizações em tempo real',
            status: 'todo',
            order: 0,
            createdAt: now,
            updatedAt: now,
            syncStatus: 'synced',
            priority: 'high',
            tags: ['backend', 'websocket'],
            assignedTo: ['user-2'],
            projectId: 'project-1',
        },
        {
            id: generateId(),
            title: 'Configurar IndexedDB',
            description: 'Implementar Dexie.js para cache offline',
            status: 'in-progress',
            order: 0,
            createdAt: now,
            updatedAt: now,
            syncStatus: 'synced',
            priority: 'high',
            tags: ['frontend', 'offline'],
            assignedTo: ['user-1'],
            projectId: 'project-1',
        },
        {
            id: generateId(),
            title: 'Testes E2E',
            description: 'Criar testes com Playwright simulando perda de conexão',
            status: 'done',
            order: 0,
            createdAt: now,
            updatedAt: now,
            syncStatus: 'synced',
            priority: 'medium',
            tags: ['testing', 'e2e'],
            assignedTo: ['user-1', 'user-2'],
            projectId: 'project-1',
        },
        {
            id: generateId(),
            title: 'Design System',
            description: 'Criar componentes reutilizáveis com Tailwind',
            status: 'todo',
            order: 0,
            createdAt: now,
            updatedAt: now,
            syncStatus: 'synced',
            priority: 'medium',
            tags: ['design', 'ui'],
            assignedTo: ['user-3'],
            projectId: 'project-2',
        },
        {
            id: generateId(),
            title: 'Drag and Drop',
            description: 'Implementar @dnd-kit para movimentação de tarefas',
            status: 'in-progress',
            order: 0,
            createdAt: now,
            updatedAt: now,
            syncStatus: 'synced',
            priority: 'high',
            tags: ['frontend', 'dnd'],
            assignedTo: ['user-1'],
            projectId: 'project-1',
        },
        {
            id: generateId(),
            title: 'Campanha de Lançamento',
            description: 'Planejar marketing para o lançamento',
            status: 'todo',
            order: 0,
            createdAt: now,
            updatedAt: now,
            syncStatus: 'synced',
            priority: 'urgent',
            tags: ['marketing', 'launch'],
            assignedTo: ['user-2', 'user-4'],
            projectId: 'project-3',
        },
    ];

    return { initialTasks, initialUsers, initialProjects };
};